const PREFIX = 'TRENDING';

const ActionType = {
  SET_MOVIES: `${PREFIX}/SET_MOVIES`,
  SET_TV: `${PREFIX}/SET_TV`,
  SET_PERSONS: `${PREFIX}/SET_PERSONS`,
  SET_LOADING: `${PREFIX}/SET_LOADING`,
  SET_ERROR: `${PREFIX}/SET_ERROR`,
  RESET_TRENDINGS: `${PREFIX}/RESET_TRENDINGS`,
};

export default ActionType;
