const PREFIX = 'TV_SERIES';

const ActionType = {
  SET_TV_SERIES: `${PREFIX}/SET_TV_SERIES`,
  SET_MORE_TV_SERIES: `${PREFIX}/SET_MORE_TV_SERIES`,
  SET_LOADING: `${PREFIX}/SET_LOADING`,
  SET_ERROR: `${PREFIX}/SET_ERROR`,
  RESET_TV_SERIES: `${PREFIX}/RESET_TV_SERIES`,
};

export default ActionType;
